### PR TITLE
Dont bug if a VTODO has no startDate

### PR DESCRIPTION
**Pull request by aenario**
Potential fix for https://github.com/cozy/cozy-calendar/issues/298

@jsilvestre , you were the last one to touch this. Please Review.

### CODE REVIEW

**Comment by aenario** [comment]
(sorry @frankrousseau  for wrong assignation)

**Comment by frankrousseau** [comment]
Oups, sorry I merged it.

**Comment by clochix** [comment]
@jsilvestre can you have a look at this please ?
Then could someone update the version, son we don't forget to publish the fix ?
Thanks ☺

**Comment by aenario** [comment]
Released as 1.1.10

**Pull request merged**
