### PR TITLE
Fix bug with details rendering

### PR DESCRIPTION
**Pull request by coen-hyde**
When parsing an existing ical file then calling toString() on the calendar object details were omitted. This patch includes the details. A refactor is probably in order to consolidate how the details are stored in VComponent. Details are stored as objects, strings and arrays.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you @coen-hyde for this contribution. @jsilvestre @jacquarg, could you review it?

**Comment by jsilvestre** [comment]
It looks good to me, thank you @coen-hyde

**Comment by frankrousseau** [comment]
@aenario can you publish this version?

Thakn you @coen-hyde

**Comment by aenario** [comment]
done as v1.1.8

**Comment by coen-hyde** [comment]
Thanks for the supper quick merge guys!

**Pull request merged**
